#**NUMPY**

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4])  #List to array convertion
a

array([1, 2, 3, 4])

In [ ]:
b = np.array([[1,2],
              [3,4],
              [5,6]])    #nested list ba 2D array
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a.shape  # shape dekhar jonno

(4,)

In [ ]:
b.shape  #out -> row,col

(3, 2)

In [ ]:
a.shape , b.shape

((4,), (3, 2))

In [ ]:
c = np.zeros((3,4))  #eta diye 0 er 2d array banano hoy , r input dite hoy row and column number er
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
c = np.ones((3,4))  #eta diye 1 er 2d array banano hoy , r input dite hoy row and column number er
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
c = np.ones((3,4)) *8
c

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

In [ ]:
c = np.zeros((3,4)) + 8

In [ ]:
np.arange(0,10)  # starting value ney , ending value nibe , tar age porjonto nbe array er moddhe

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,12, 3)

array([0, 3, 6, 9])

In [ ]:
np.linspace(1,10,6)  #(10−1)/(6−1)=9/5=1.8     #equal spacing

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [ ]:
c.shape, c.ndim, c.dtype  # ndim diye dimention , dtype mane data type

((3, 4), 2, dtype('float64'))

In [ ]:
ami = np.array([1,2,3])

In [ ]:
ami.ndim

1

In [ ]:
tmi = np.array([[1,2],[3,4],[5,6]])

In [ ]:
tmi.ndim

2

#**Exercise 1 (quick)**

* Make a 3×3 array of all 7s
* Make numbers 1..12 and reshape to (3,4)

In [ ]:
aa = np.full((3,3), 7) # koto matrics chai ,r ki value thakbe .
aa


array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
aa.dtype

dtype('int64')

In [ ]:
alu = np.zeros((3,3)) + 7
alu


array([[7., 7., 7.],
       [7., 7., 7.],
       [7., 7., 7.]])

In [ ]:
alu.dtype

dtype('float64')

In [ ]:
np.arange(1,16)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
np.arange(1,16).reshape(3,5)  # reshape dile 1D ke 2D matrics banaite parbo ( value count thik thak dite hbe )

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#**Indexing:rgb ta 2d image , array er vasay ami 3d mat bolte pari,video ke 4d mat bolte pari . Sizing**

#**Indexing, slicing, masking**

In [ ]:
x = np.array([10,20,30,40,50])
x, x[0], x[-2] #normal array print , 0 index er value , r -1 diye last index er value

(array([10, 20, 30, 40, 50]), np.int64(10), np.int64(40))

In [ ]:
# x[begin:end]

x [:3]  # slicing kortesi , kichu dei nai : er age , mane by default starting theke shuru hbe r 3 obdi dekhabe

array([10, 20, 30])

In [ ]:
x = np.array([[1,2,3,55,56,57],
             [4,5,6,66,67,68],
             [7,8,9,99,96,97],
             [33,44,50,23,45,23]])
x

array([[ 1,  2,  3, 55, 56, 57],
       [ 4,  5,  6, 66, 67, 68],
       [ 7,  8,  9, 99, 96, 97],
       [33, 44, 50, 23, 45, 23]])

In [ ]:
x[1,1]   #row , col

np.int64(5)

In [ ]:
x[1,2]

np.int64(6)

In [ ]:
x[1,1], x[1,2]

(np.int64(5), np.int64(6))

In [ ]:
# x[row[b:e] , col[b:e]]     rows,cols
x[1 , 1:3]

array([5, 6])

In [ ]:
x[1:3, 1:3]

array([[5, 6],
       [8, 9]])

In [ ]:
x[2: , 4: ]

array([[96, 97],
       [45, 23]])

In [ ]:
# 2D indexing

M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])


In [ ]:
M[0, 1]     # 2


np.int64(2)

In [ ]:
M[:, 1]     # column 1


array([2, 5, 8])

In [ ]:
M[1, :]     # row 1


array([4, 5, 6])

In [ ]:
M[0:2, 1:3] # submatrix

array([[2, 3],
       [5, 6]])

In [ ]:
v = np.array([0.2,1.5,-0.7,3.3,2.2]) # v name ekta array create korlam

v

array([ 0.2,  1.5, -0.7,  3.3,  2.2])

#**Masking**



In [ ]:
mask = v>1    #v vector e 1 er boro jesob value ache seula ke true deo ,
mask

array([False,  True, False,  True,  True])

In [ ]:
v[mask]   #only true gula

array([1.5, 3.3, 2.2])

In [ ]:
v[mask==False] #only false gula

array([ 0.2, -0.7])

In [ ]:
v[v>1.0]

array([1.5, 3.3, 2.2])

In [ ]:
v[v <= 1.0]

array([ 0.2, -0.7])

In [ ]:
x = np.array([1, 2, 3])
y = np.array([10, 20,30])

In [ ]:
x + y  #x, y jog hocche

array([11, 22, 33])

In [ ]:
x * y

array([10, 40, 90])

In [ ]:
x = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

y = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])



In [ ]:
x+y

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [ ]:
x*y

array([[ 10,  40,  90],
       [160, 250, 360],
       [490, 640, 810]])

In [ ]:
x = np.array([
    1,2,3

])

y = np.array([
    [10,20,30],
    [40,50,60]

])



In [ ]:
x+y

array([[11, 22, 33],
       [41, 52, 63]])

In [ ]:
x*y

array([[ 10,  40,  90],
       [ 40, 100, 180]])

In [ ]:
# X: shape (n_samples, n_features)
# Here: 4 samples, 3 features
X = np.random.randn(4, 3)

print("X:\n", X)
print("Shape:", X.shape)  # (4, 3)

 # Global sum: reduces everything to a single number
print("Global sum:", X.sum())

# axis=0: reduce over rows -> gives one value per column (per feature)   col borabar
print("Sum per feature (axis=0):", X.sum(axis=0))

# axis=1: reduce over columns -> gives one value per row (per sample)    row borabor
print("Sum per sample (axis=1):", X.sum(axis=1))

X:
 [[-0.24516658  0.28376033  1.08103841]
 [ 0.83569934  0.83738606 -0.11412143]
 [-0.8500174   0.01437666  0.09340523]
 [-1.61604622 -1.13265758  1.64522496]]
Shape: (4, 3)
Global sum: 0.8328817656719536
Sum per feature (axis=0): [-1.87553087  0.00286546  2.70554717]
Sum per sample (axis=1): [ 1.11963215  1.55896397 -0.74223552 -1.10347884]


In [ ]:
#Mean, std, min, max (common in preprocessing)
# Feature-wise mean (1 value per feature)
mu = X.mean(axis=0)
print("Mean per feature:", mu)

#overall mean
mu = X.mean()
print(mu)

# Feature-wise std (1 value per feature)
sigma = X.std(axis=0)
print("Std per feature:", sigma)

# Feature-wise min/max
print("Min per feature:", X.min(axis=0))
print("Max per feature:", X.max(axis=0))

Mean per feature: [-0.46888272  0.00071637  0.67638679]
0.06940681380599613
Std per feature: [0.89627437 0.71847985 0.71888126]
Min per feature: [-1.61604622 -1.13265758 -0.11412143]
Max per feature: [0.83569934 0.83738606 1.64522496]


In [ ]:
A = np.ones((3, 2))
B = np.zeros((3, 2))
print(A)
print(B)




[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
# Concatenate along axis=1 => append columns (more features)
C_feat = np.concatenate([A, B], axis=1)
print("Feature concat (axis=1):\n", C_feat)
print("Shape:", C_feat.shape)  # (3, 4)



Feature concat (axis=1):
 [[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]
Shape: (3, 4)


In [ ]:
# Concatenate along axis=0 => append rows (more samples)
C_samp = np.concatenate([A, B], axis=0)
print("Sample concat (axis=0):\n", C_samp)
print("Shape:", C_samp.shape)  # (6, 2)



Sample concat (axis=0):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
Shape: (6, 2)


In [ ]:
# vstack/hstack are convenience wrappers (mostly for 2D)
print("vstack shape:", np.vstack([A, B]).shape)
print("hstack shape:", np.hstack([A, B]).shape)

vstack shape: (6, 2)
hstack shape: (3, 4)


In [ ]:
np.vstack([A, B])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
# A, B, np.vstack([A, B])
np.concatenate([A,B], axis=1).sum(axis=0)

array([3., 3., 0., 0.])




#**Exercise 2**

given: v = np.array([1, 4, 2, 9, 5, 3])

* Select values >= 4<br>
*	Replace values < 4 with 0 <br>
*	Get indices where v is even




In [ ]:
v = np.array([1, 4, 2, 9, 5, 3])

In [ ]:
v

array([1, 4, 2, 9, 5, 3])

In [ ]:
#Select values >= 4
v[v>=4]


array([4, 9, 5])

In [ ]:
#Replace values < 4 with 0
v2 = v.copy()
v2[v2 < 4] = 0
v2

array([0, 4, 0, 9, 5, 0])

In [ ]:
#Get indices where v is even
#v = np.array([1, 4, 2, 9, 5, 3])
np.where(v % 2 == 0)



(array([1, 2]),)

#**সংক্ষেপে মনে রাখো শর্ত দিয়ে**
* select → v[condition]

* replace → v[condition] = value

* index বের করতে → np.where(condition)




#**Vectorization & Broadcasting**

In [ ]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
x + y


array([11, 22, 33])

In [ ]:
x * y


array([10, 40, 90])

In [ ]:
np.sqrt(y)

array([3.16227766, 4.47213595, 5.47722558])

In [ ]:

X = np.random.randn(5, 3)        # 5 samples, 3 features


In [ ]:
X

array([[ 0.17494739, -0.36067881,  0.01607949],
       [ 0.80624339, -0.93130825,  1.7436379 ],
       [-0.85119698,  0.92632749,  0.48431168],
       [-1.09448121, -0.80216662,  0.75294737],
       [ 0.92805537, -2.25420491, -0.82846584]])

In [ ]:

X = np.random.randn(5)        # 5 samples
X


array([ 0.84546031, -0.16823206, -1.03545662, -2.06733168, -1.20799946])

In [ ]:
mu = X.mean(axis=0)              # (3,)


In [ ]:
mu

np.float64(-0.7267119006093642)

In [ ]:
X_centered = X - mu

In [ ]:
X_centered

array([[ 0.66696855, -0.72403542,  0.4011648 ],
       [ 0.56879312,  0.10730969, -0.19144604],
       [-0.9511627 ,  0.63092294,  1.20055645],
       [-0.94603645,  0.33355986, -0.8359503 ],
       [ 0.66143748, -0.34775707, -0.57432491]])


#**Exercise 3**

*	Create X shape (6, 2) random
* Compute feature-wise mean and std
* Standardize: X_std = (X - mean) / std

In [ ]:
# a
import numpy as np

X = np.random.rand(6, 2)
X


array([[0.11814434, 0.59540968],
       [0.49624039, 0.27975336],
       [0.91346183, 0.34190858],
       [0.52092236, 0.8300837 ],
       [0.85072977, 0.25586257],
       [0.07074433, 0.76351824]])

In [ ]:
# b
mean = X.mean(axis=0)
std = X.std(axis=0)

In [ ]:
#c
X_std = (X - mean) / std
X_std


array([[-1.16838662,  0.36519371],
       [ 0.00371968, -1.00192272],
       [ 1.29711558, -0.73272672],
       [ 0.08023433,  1.38157352],
       [ 1.10264475, -1.10539441],
       [-1.31532773,  1.09327661]])

#**ML-style reductions**
In ML, we often compute statistics per feature (column) across samples (rows):

*	mean/std for normalization
*	min/max for scaling
*	sums for loss/gradients
*	covariance for feature relationships

In [ ]:
# X: shape (n_samples, n_features)
# Here: 4 samples, 3 features
X = np.random.randn(4, 3)

print("X:\n", X)
print("Shape:", X.shape)  # (4, 3)

 # Global sum: reduces everything to a single number
print("Global sum:", X.sum())

# axis=0: reduce over rows -> gives one value per column (per feature)
print("Sum per feature (axis=0):", X.sum(axis=0))

# axis=1: reduce over columns -> gives one value per row (per sample)
print("Sum per sample (axis=1):", X.sum(axis=1))

X:
 [[-0.94280414  1.04693008 -0.98456245]
 [-0.58799654  0.35495591 -0.5134047 ]
 [-1.96660667 -0.25850944  0.03110258]
 [-1.03084327  1.906369   -0.15593182]]
Shape: (4, 3)
Global sum: -3.1013014422619634
Sum per feature (axis=0): [-4.52825061  3.04974555 -1.62279639]
Sum per sample (axis=1): [-0.8804365  -0.74644533 -2.19401353  0.71959392]


In [ ]:

#Mean, std, min, max (common in preprocessing)
# Feature-wise mean (1 value per feature)
mu = X.mean(axis=0)
print("Mean per feature:", mu)

# Feature-wise std (1 value per feature)
sigma = X.std(axis=0)
print("Std per feature:", sigma)

# Feature-wise min/max
print("Min per feature:", X.min(axis=0))
print("Max per feature:", X.max(axis=0))

Mean per feature: [-1.13206265  0.76243639 -0.4056991 ]
Std per feature: [0.50954288 0.80589844 0.38725401]
Min per feature: [-1.96660667 -0.25850944 -0.98456245]
Max per feature: [-0.58799654  1.906369    0.03110258]


In [ ]:

#standardization z-score

# Standardization: (X - mean) / std
# Broadcasting: mu and sigma (shape (3,)) are applied across all rows
X_std = (X - mu) / (sigma + 1e-8)  # small epsilon to avoid divide-by-zero
print("Standardized X:\n", X_std)

# Check standardized stats (should be ~0 mean and ~1 std per feature)
print("Std mean per feature:", X_std.mean(axis=0))
print("Std std per feature:", X_std.std(axis=0))

Standardized X:
 [[ 0.37142804  0.35301432 -1.49478978]
 [ 1.06775331 -0.50562261 -0.27812649]
 [-1.63782878 -1.26684177  1.12794613]
 [ 0.19864743  1.41945006  0.64497014]]
Std mean per feature: [-1.04083409e-16  0.00000000e+00  0.00000000e+00]
Std std per feature: [0.99999998 0.99999999 0.99999997]


Exercise 4 (more ML-relevant)

Create random data X of shape (100, 4). Compute:

1.	per-feature mean
2.	per-feature variance
3.	covariance matrix (feature-feature relationship)

In [ ]:
'''
'''

#**Common NumPy mistakes**


In [ ]:
xx = np.arange(1,16).reshape(5,3)
xx

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
ww = np.array([1,2,3])
ww

array([1, 2, 3])

In [ ]:
xx * ww

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27],
       [10, 22, 36],
       [13, 28, 45]])

In [ ]:
xx @ ww

array([14, 32, 50, 68, 86])

In [ ]:
import numpy as np

In [ ]:
# Mistake 1: Confusing * with @

X = np.random.randn(5, 3)
w = np.random.randn(3)

# Correct matrix-vector multiplication
y1 = X @ w

# Wrong: elementwise multiply (will broadcast and give (5,3))
y2 = X * w

print("X @ w shape:", y1.shape)  # (5,)
print("X * w shape:", y2.shape)  # (5, 3)

X @ w shape: (5,)
X * w shape: (5, 3)


In [ ]:
'''
চল একদম **intuition + exam-friendly** ভাবে বুঝাই 👌

এই কোডটা আসলে **NumPy তে খুব common একটা mistake** বোঝাচ্ছে।

---

## 🔴 Mistake 1: `*` আর `@` এক জিনিস ভাবা

### 🔹 Data কী আছে আগে দেখি

```python
X = np.random.randn(5, 3)   # 5 rows, 3 columns
w = np.random.randn(3)      # length 3 vector
```

মানে:

* `X` → ৫টা data point, প্রত্যেকটার ৩টা feature
* `w` → weight vector (৩টা weight)

---

## ✅ Correct: `@` (matrix-vector multiplication)

```python
y1 = X @ w
```

এটা গণিতে যা হচ্ছে:

```
(5×3)  dot  (3×1)  =  (5×1)
```

প্রত্যেক row এর সাথে `w` এর **dot product**

Output:

```python
y1.shape  → (5,)
```

👉 একদম **linear model output**
👉 Machine Learning এ যেটা চাই

---

## ❌ Wrong: `*` (element-wise multiplication)

```python
y2 = X * w
```

এখানে কী হচ্ছে?

* `w` এর shape `(3,)`
* NumPy **broadcast** করে:

  ```
  w → (1,3) → (5,3)
  ```
* তারপর element-by-element multiply

Result:

```python
y2.shape → (5, 3)
```

👉 কোনো summation হয়নি
👉 এটা **dot product না**
👉 ML output হিসেবে ভুল

---

## 🔍 ছোট উদাহরণ দিয়ে বুঝি

ধরি:

```
X row = [x1, x2, x3]
w     = [w1, w2, w3]
```

### `@` করলে:

```
x1*w1 + x2*w2 + x3*w3   → 1টা সংখ্যা
```

### `*` করলে:

```
[x1*w1, x2*w2, x3*w3]   → 3টা সংখ্যা
```

---

## 🧠 এক লাইনে বোঝা (exam answer)

> `@` ব্যবহার হয় **matrix / vector multiplication** এর জন্য
> `*` ব্যবহার হয় **element-wise multiplication** এর জন্য
> NumPy তে দুটো এক জিনিস না

---

## 🔑 মনে রাখার trick

* **ML / Linear Algebra** → `@`
* **Same shape element-by-element কাজ** → `*`

চাও তো আমি এটা দিয়ে
👉 **linear regression prediction**
👉 বা **neural network forward pass**
খুব সহজ example এ দেখাতে পারি 😄
''''

In [ ]:
'''
চল একদম **হাতেকলমে, সংখ্যাসহ** বুঝাই—তাহলে মাথায় গেঁথে যাবে 👍

---

## 🔢 Simple example (no random)

### ধরি:

```python
import numpy as np

X = np.array([
    [1, 2, 3],
    [4, 5, 6]
])          # shape (2,3)

w = np.array([10, 20, 30])   # shape (3,)
```

মানে:

* 2টা data point
* প্রত্যেকটার 3টা feature
* `w` = weight vector

---

## ✅ Correct: `@` (dot product)

```python
y1 = X @ w
print(y1)
print(y1.shape)
```

### কী হচ্ছে ভেতরে?

Row by row হিসাব:

**Row 1**

```
1*10 + 2*20 + 3*30
= 10 + 40 + 90
= 140
```

**Row 2**

```
4*10 + 5*20 + 6*30
= 40 + 100 + 180
= 320
```

### Output:

```
[140 320]
(2,)
```

👉 প্রতিটা row থেকে **একটা output**
👉 এটাই linear regression / NN এ দরকার

---

## ❌ Wrong: `*` (element-wise)

```python
y2 = X * w
print(y2)
print(y2.shape)
```

### কী হচ্ছে?

NumPy `w` কে broadcast করে:

```
w = [10, 20, 30]
↓
[10, 20, 30]
[10, 20, 30]
```

তারপর element-wise multiply:

```
[
 [1*10, 2*20, 3*30],
 [4*10, 5*20, 6*30]
]
```

### Output:

```
[[ 10  40  90]
 [ 40 100 180]]
(2, 3)
```

👉 কোনো যোগ (sum) হয়নি
👉 এটা **dot product না**

---

## 🧠 Visual summary

| Operation       | Code    | Output shape | মানে    |
| --------------- | ------- | ------------ | ------- |
| Matrix × Vector | `X @ w` | `(2,)`       | ✔️ সঠিক |
| Element-wise    | `X * w` | `(2,3)`      | ❌ ভুল   |

---

## 📝 One-line exam answer

> `@` ব্যবহার করলে row-wise dot product হয়,
> `*` ব্যবহার করলে শুধু element-by-element multiplication হয়।

---

চাও তো আমি দেখাতে পারি:

* কেন `X @ w` = prediction
* আর `X * w` কে কিভাবে ঠিক করে sum করলে same result পাওয়া যায়

বললেই হবে 😄
'''

In [ ]:
a = np.random.randn(5)      # shape (5,)
a


array([ 1.08481828,  1.71139333,  0.21472396,  0.74329331, -1.31440533])

In [ ]:
b = np.random.randn(5, 1)   # shape (5,1)
b

array([[-2.15775568],
       [-0.43428225],
       [ 0.93140431],
       [ 0.73182742],
       [ 0.59835835]])

In [ ]:
# Mistake 2: (n,) vs (n,1) broadcasting trap

a = np.random.randn(5)      # shape (5,)
b = np.random.randn(5, 1)   # shape (5,1)

print("a shape:", a.shape)
print("b shape:", b.shape)

# This broadcasts into a (5,5) matrix unintentionally
c = a + b
print("a + b shape:", c.shape)  # (5,5) surprise!

a shape: (5,)
b shape: (5, 1)
a + b shape: (5, 5)


In [ ]:
'''
চল এটা **খুব পরিষ্কার, ধাপে ধাপে** বুঝাই—এটা NumPy-র সবচেয়ে dangerous broadcasting trap 😄

---

## 🔴 Mistake 2: `(n,)` vs `(n,1)` আলাদা জিনিস

### আগে shape গুলো দেখি

```python
a = np.random.randn(5)      # shape (5,)
b = np.random.randn(5, 1)   # shape (5,1)
```

মানে:

* `a` → **1D vector**

  ```
  [a1 a2 a3 a4 a5]
  ```
* `b` → **column vector**

  ```
  [[b1],
   [b2],
   [b3],
   [b4],
   [b5]]
  ```

---

## ❌ এখন এই লাইনটা দেখো

```python
c = a + b
```

NumPy কী করে?

### 🔹 Broadcasting rule অনুযায়ী:

* `a (5,)` কে ধরে নেয় → `(1,5)`
* `b (5,1)` ঠিকই আছে

এখন shapes:

```
(1,5)
(5,1)
```

এগুলো broadcast হয়ে যায়:

```
(5,5)
```

---

## 🔍 আসলে কী হচ্ছে (visual)

```
a → [a1 a2 a3 a4 a5]
     [a1 a2 a3 a4 a5]
     [a1 a2 a3 a4 a5]
     [a1 a2 a3 a4 a5]
     [a1 a2 a3 a4 a5]

b → [b1]
     [b2]
     [b3]
     [b4]
     [b5]
```

Add করলে:

```
c =
[b1+a1 b1+a2 b1+a3 b1+a4 b1+a5]
[b2+a1 b2+a2 b2+a3 b2+a4 b2+a5]
[b3+a1 b3+a2 b3+a3 b3+a4 b3+a5]
[b4+a1 b4+a2 b4+a3 b4+a4 b4+a5]
[b5+a1 b5+a2 b5+a3 b5+a4 b5+a5]
```

👉 তাই:

```python
c.shape → (5,5)
```

💥 **surprise!**

---

## ✅ ঠিক কী চেয়েছিলে তুমি?

### Case 1️⃣: element-wise add (5 elements)

```python
c = a + b.ravel()   # or b.squeeze()
print(c.shape)     # (5,)
```

### Case 2️⃣: column vector output (5,1)

```python
c = a.reshape(5,1) + b
print(c.shape)     # (5,1)
```

---

## 🧠 Golden rule (exam + real life)

> **NumPy তে `(n,)` ≠ `(n,1)`**
> 1D vector আর column vector এক জিনিস না

---

## 🔑 Memory trick

* `(n,)` → lazy, dangerous 😅
* `(n,1)` → explicit, safe

👉 ML / Linear Algebra এ সবসময় **shape print করে check করো**

চাও তো আমি দেখাতে পারি:

* কেন ML code এ `(n,1)` বেশি safe
* gradient descent এ এই ভুল হলে কী ভয়ংকর bug হয় 😬
'''

In [ ]:
# fix explicitly reshape

a_col = a.reshape(-1, 1)  # (5,1)
print("a_col + b shape:", (a_col + b).shape)  # (5,1)

a_col + b shape: (5, 1)


In [ ]:
a = np.arange(1,6)      # shape (5,)
b = np.arange(1, 6).reshape(5,1)   # shape (5,1)

print("a shape:", a.shape)
print("b shape:", b.shape)

d = a.reshape(1,-1)

c = d + b
c


a shape: (5,)
b shape: (5, 1)


array([[ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10]])

In [ ]:
a = np.arange(1,6)      # shape (5,)
b = np.arange(1, 6).reshape(5,1)   # shape (5,1)

print("a shape:", a.shape)
print("b shape:", b.shape)

d = a.reshape(-1,1)

c = d + b
c

a shape: (5,)
b shape: (5, 1)


array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10]])

In [ ]:
a = np.arange(1,6)      # shape (5,)
b = np.arange(1, 6).reshape(5,1)   # shape (5,1)

print("a shape:", a.shape)
print("b shape:", b.shape)

d = b.reshape(1,-1)

c = d + a
c

a shape: (5,)
b shape: (5, 1)


array([[ 2,  4,  6,  8, 10]])

In [ ]:
x_row = np.array([1,2,3]).reshape(1, -1)   # (1,3)
x_col = np.array([1,2,3]).reshape(-1, 1)   # (3,1)

x_row, x_col

(array([[1, 2, 3]]),
 array([[1],
        [2],
        [3]]))

In [ ]:
# a is a 1D vector with 12 elements
a = np.arange(12)
print("a:", a)
print("a shape:", a.shape)  # (12,)

# Reshape into a matrix: 3 rows, 4 columns
a= a.reshape(3, 4)
a

a: [ 0  1  2  3  4  5  6  7  8  9 10 11]
a shape: (12,)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:

a.min(), a.max(), a.sum()

(np.int64(0), np.int64(11), np.int64(66))

In [ ]:
a.sum(axis=0) #col

array([12, 15, 18, 21])

In [ ]:
a.sum(axis=1) #row

array([ 6, 22, 38])

#*Reshaping & stacking (ML data engineering)*

Why this matters in ML

*	Reshape is used for flattening images, making batches, aligning shapes for matrix math
* Stacking is used when combining datasets, adding features, adding bias terms

In [ ]:
# a is a 1D vector with 12 elements
a = np.arange(12)
print("a:", a)
print("a shape:", a.shape)  # (12,)

# Reshape into a matrix: 3 rows, 4 columns
A = a.reshape(3, 4)
print("A:\n", A)
print("A shape:", A.shape)  # (3, 4)

# Transpose swaps rows/columns
print("A.T:\n", A.T)
print("A.T shape:", A.T.shape)  # (4, 3)

a: [ 0  1  2  3  4  5  6  7  8  9 10 11]
a shape: (12,)
A:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
A shape: (3, 4)
A.T:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
A.T shape: (4, 3)


In [ ]:

A = np.ones((3, 2))
B = np.zeros((3, 2))

# Concatenate along axis=1 => append columns (more features)
C_feat = np.concatenate([A, B], axis=1)
print("Feature concat (axis=1):\n", C_feat)
print("Shape:", C_feat.shape)  # (3, 4)

# Concatenate along axis=0 => append rows (more samples)
C_samp = np.concatenate([A, B], axis=0)
print("Sample concat (axis=0):\n", C_samp)
print("Shape:", C_samp.shape)  # (6, 2)

# vstack/hstack are convenience wrappers (mostly for 2D)
print("vstack shape:", np.vstack([A, B]).shape)
print("hstack shape:", np.hstack([A, B]).shape)

Feature concat (axis=1):
 [[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]
Shape: (3, 4)
Sample concat (axis=0):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
Shape: (6, 2)
vstack shape: (6, 2)
hstack shape: (3, 4)


In [ ]:
#ML-style reductions

In ML, we often compute statistics per feature (column) across samples (rows):

•	mean/std for normalization
•	min/max for scaling
•	sums for loss/gradients
•	covariance for feature relationships

In [ ]:
# X: shape (n_samples, n_features)
# Here: 4 samples, 3 features
X = np.random.randn(4, 3)

print("X:\n", X)
print("Shape:", X.shape)  # (4, 3)

 # Global sum: reduces everything to a single number
print("Global sum:", X.sum())

# axis=0: reduce over rows -> gives one value per column (per feature)
print("Sum per feature (axis=0):", X.sum(axis=0))

# axis=1: reduce over columns -> gives one value per row (per sample)
print("Sum per sample (axis=1):", X.sum(axis=1))

X:
 [[-0.44730548  0.13559127 -0.43884835]
 [-0.21454254 -0.25727811  1.74833048]
 [ 0.75665428  0.66279081 -0.20604605]
 [-0.54469223 -0.28649933  0.94435882]]
Shape: (4, 3)
Global sum: 1.852513576599815
Sum per feature (axis=0): [-0.44988597  0.25460464  2.04779491]
Sum per sample (axis=1): [-0.75056256  1.27650984  1.21339905  0.11316726]


In [ ]:

#Mean, std, min, max (common in preprocessing)
# Feature-wise mean (1 value per feature)
mu = X.mean(axis=0)
print("Mean per feature:", mu)

# Feature-wise std (1 value per feature)
sigma = X.std(axis=0)
print("Std per feature:", sigma)

# Feature-wise min/max
print("Min per feature:", X.min(axis=0))
print("Max per feature:", X.max(axis=0))

Mean per feature: [-0.11247149  0.06365116  0.51194873]
Std per feature: [0.51592797 0.38397417 0.88531773]
Min per feature: [-0.54469223 -0.28649933 -0.43884835]
Max per feature: [0.75665428 0.66279081 1.74833048]


In [ ]:
#standardization z-score

# Standardization: (X - mean) / std
# Broadcasting: mu and sigma (shape (3,)) are applied across all rows
X_std = (X - mu) / (sigma + 1e-8)  # small epsilon to avoid divide-by-zero
print("Standardized X:\n", X_std)

# Check standardized stats (should be ~0 mean and ~1 std per feature)
print("Std mean per feature:", X_std.mean(axis=0))
print("Std std per feature:", X_std.std(axis=0))

Standardized X:
 [[-0.64899366  0.18735662 -1.0739614 ]
 [-0.19783972 -0.83580949  1.39654014]
 [ 1.6845874   1.56036442 -0.81100236]
 [-0.83775402 -0.91191155  0.48842362]]
Std mean per feature: [ 0.00000000e+00  5.55111512e-17 -2.77555756e-17]
Std std per feature: [0.99999998 0.99999997 0.99999999]


Exercise 4 (more ML-relevant)

Create random data X of shape (100, 4). Compute:

1.	per-feature mean
2.	per-feature variance
3.	covariance matrix (feature-feature relationship)

In [ ]:
# TODO: Create X with 100 samples and 4 features
X = np.random.randn(100, 4)

# 1) Mean per feature
mu = X.mean(axis=0)

# 2) Variance per feature
var = X.var(axis=0)

# 3) Covariance matrix (4x4), rowvar=False => columns are variables (features)
cov = np.cov(X, rowvar=False)

print("Mean:", mu)
print("Variance:", var)
print("Covariance matrix:\n", cov)
print("Cov shape:", cov.shape)  # should be (4, 4)

Mean: [-0.01582337 -0.04997871 -0.05444944  0.10847075]
Variance: [0.90917656 0.81209117 1.2642639  0.98571552]
Covariance matrix:
 [[ 0.91836016  0.01595545 -0.09368523  0.02304372]
 [ 0.01595545  0.82029411 -0.17046671  0.09866377]
 [-0.09368523 -0.17046671  1.27703424 -0.09001655]
 [ 0.02304372  0.09866377 -0.09001655  0.99567225]]
Cov shape: (4, 4)


In [ ]:
'''
ঠিক আছে 🙂
এই অংশটাই সবাই প্রথমে **confusing লাগে**, তাই একদম **slow + visual** করে বুঝাই।

---

## আগে একটা কথা খুব পরিষ্কার করি

```python
cov = np.cov(X, rowvar=False)
```

এখানে **২টা প্রশ্নের উত্তর দরকার**:

1️⃣ Covariance matrix জিনিসটা কী?
2️⃣ `rowvar=False` না দিলে কী ভুল হবে?

---

## 1️⃣ Covariance matrix মানে কী? (human language)

ধরো তোমার 4টা feature আছে:

* Feature 1
* Feature 2
* Feature 3
* Feature 4

**Covariance matrix বলে দেয়:**

> “Feature i বাড়লে Feature j সাধারণত বাড়ে নাকি কমে?”

তাই matrix টা হয় **feature × feature**

👉 4 feature ⇒ **4 × 4 matrix**

---

## 2️⃣ তোমার X দেখতে কেমন?

```python
X.shape = (100, 4)
```

মানে:

* 100টা sample (row)
* 4টা feature (column)

ভিজুয়ালি:

```
        f1   f2   f3   f4
sample1
sample2
sample3
...
sample100
```

✔️ **Column = feature**
✔️ **Row = sample**

---

## 3️⃣ np.cov() default behaviour (এটাই trap)

```python
np.cov(X)
```

ডিফল্ট ধরে নেয়:

> ❌ **Row = variable (feature)**
> ❌ **Column = observation (sample)**

কিন্তু তোমার ডেটা এমন না!

তাই numpy ভাবে:

* তোমার **100টা row = 100টা variable**
* result হবে **100 × 100 matrix** 😱

---

## 4️⃣ rowvar=False দিলে কী হয়? (main point 🔥)

```python
np.cov(X, rowvar=False)
```

এখন তুমি numpy কে বলছো:

> ✅ “Row না, **column-ই variable (feature)**”

মানে:

* Column = feature ✔️
* Row = sample ✔️

এখন numpy ঠিক বুঝতে পারে।

---

## 5️⃣ তখন ভেতরে কী হিসাব হয়?

NumPy কার্যত এটা করে:

```
cov =
[
 cov(f1,f1) cov(f1,f2) cov(f1,f3) cov(f1,f4)
 cov(f2,f1) cov(f2,f2) cov(f2,f3) cov(f2,f4)
 cov(f3,f1) cov(f3,f2) cov(f3,f3) cov(f3,f4)
 cov(f4,f1) cov(f4,f2) cov(f4,f3) cov(f4,f4)
]
```

👉 তাই shape হয়:

```python
(4, 4)
```

---

## 6️⃣ খুব ছোট example (2 sample, 2 feature)

```python
X = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
# shape (3 samples, 2 features)
```

### ❌ ভুল

```python
np.cov(X)
# output shape (3,3)  ❌
```

### ✅ ঠিক

```python
np.cov(X, rowvar=False)
# output shape (2,2)  ✅
```

---

## 🧠 এক লাইনের golden rule (exam perfect)

> **যদি X.shape = (samples, features) হয়,
> তাহলে np.cov(X, rowvar=False) দিতে হবে।**

---

## 🔑 মনে রাখার trick

* **ML world** → rows = samples, columns = features
* **NumPy default** → rows = variables
  👉 তাই `rowvar=False` লাগেই

যদি চাও, আমি এটাকে **PCA intuition** বা **correlation matrix** দিয়ে আরেকবার দেখাতে পারি—বললেই হলো 😊
'''

In [ ]:
'''
ঠিক আছে—এবার একদম **“কেন এটা দরকার, না দিলে কী ভুল হয়”** এই লেভেলে নামি।
কোনো jargon না, শুধু দরকারি কথা 👇

---

## এক লাইনে আগে উত্তর দিই

```python
cov = np.cov(X, rowvar=False)
```

👉 **এটা দিয়ে তুমি 4টা feature একে–অপরের সাথে কিভাবে বদলায় (relation) সেটা বের করছো।**
👉 `rowvar=False` না দিলে NumPy **ভুল জিনিসের relation** বের করে ফেলত।

---

## এখন একদম বাস্তব উদাহরণ

ধরো তোমার ডেটা এটা:

```
X =
[ height  weight  age  salary ]
[ 170     65      22   30000  ]
[ 160     55      21   28000  ]
[ 180     75      25   40000  ]
...
```

* **row = মানুষ (sample)**
* **column = feature (height, weight, …)**

---

## তুমি আসলে কী জানতে চাও?

❓ প্রশ্ন:

> “height বাড়লে weight কি বাড়ে?”
> “age আর salary এর relation কী?”

👉 এই প্রশ্নের উত্তরই **covariance matrix**।

তাই দরকার:

* height ↔ weight
* height ↔ age
* salary ↔ age
  …সব feature–feature relation

মানে:

```
feature × feature = 4 × 4
```

---

## এখন problem কোথায়?

### NumPy default ভাবে ধরে নেয়:

> “Row গুলাই variable”

কিন্তু তোমার ক্ষেত্রে:

* row = মানুষ ❌
* column = variable (feature) ✔️

তাই যদি তুমি লেখো:

```python
np.cov(X)
```

NumPy ভাবে:

> “100 জন মানুষের মধ্যে সম্পর্ক বের করতে হবে”

🤯 **এটা তুমি চাও নাই**

---

## `rowvar=False` দিলে কী হলো?

```python
np.cov(X, rowvar=False)
```

তুমি NumPy কে বললে:

> ❗ “শোন, row না—**column গুলাই variable**”

এখন NumPy ঠিক বোঝে:

* variable = height, weight, age, salary
* তাই relation বের করে **feature ↔ feature**

---

## খুব blunt ভাবে বললে 😅

* `rowvar=False`
  👉 “এই ডেটার column গুলাই আসল জিনিস”

* না দিলে
  👉 NumPy ভুল মানুষ ধরে relation বের করে

---

## Final picture (মাথায় রাখার মতো)

| তুমি চাও                              | কোড                       |
| ------------------------------------- | ------------------------- |
| feature–feature relation              | `np.cov(X, rowvar=False)` |
| sample–sample relation (almost never) | `np.cov(X)`               |

---

## এক লাইনের exam-style answer

> `rowvar=False` ব্যবহার করা হয় যাতে covariance **features (columns)** এর মধ্যে হিসাব হয়, না যে samples (rows) এর মধ্যে।

এখন যদি চাও, আমি এটা **একটা 2-feature, 3-sample example** দিয়ে হাতে হিসাব করে দেখাতে পারি—তখন আর ভুল হবে না।
'''

#*QUIZ_1*

#**Q1 (NumPy shapes)**
Given

import numpy as np
X = np.random.randn(100, 3)
w = np.array([1.0, 2.0, 3.0])
y_hat = X @ w

1.What is the shape of X, w, and y_hat? Print the shapes to show.

In [ ]:
import numpy as np
X = np.random.randn(100, 3)
w = np.array([1.0, 2.0, 3.0])
y_hat = X @ w

X.shape,w.shape,y_hat.shape

((100, 3), (3,), (100,))

Q2 (Feature-wise reductions)

Given X with shape (n_samples, n_features):

X = np.random.randn(50, 4)

Write code to compute:

Mean per feature
Standard deviation per feature

In [ ]:
X = np.random.randn(50, 4)
mu = X.mean(axis = 0)
sigma = X.std(axis=0)
mu,sigma

(array([-0.19093199,  0.14874525, -0.21163196, -0.067746  ]),
 array([0.82119423, 1.02880485, 0.96489777, 0.82777544]))

# **PANDAS**
---




In [ ]:
import pandas as pd
#pandas holo dataframe library , statistical analysis kora hoy
#dataload , clean , analyse , preprocess
#load = load kore niye asha
#clean = rainy / rain / very rainy -> rain , ek form e niye asha
#analyse kora
#preprocess = data prepare kora

In [ ]:
df = pd.read_csv('weather.csv')  #csv, xlsx , .db etc file read kora jay
df

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0    1/1/2016           38        23        52                 30.03   
1    1/2/2016           36        18        46                 30.02   
2    1/3/2016           40        21        47                 29.86   
3    1/4/2016           25         9        44                 30.05   
4    1/5/2016           20        -3        41                 30.57   
5    1/6/2016           33         4        35                 30.50   
6    1/7/2016           39        11        33                 30.28   
7    1/8/2016           39        29        64                 30.20   
8    1/9/2016           44        38        77                 30.16   
9   1/10/2016           50        46        71                 29.59   
10  1/11/2016           33         8        37                 29.92   
11  1/12/2016           35        15        53                 29.85   
12  1/13/2016           26         4        42                 29.94   
13  1/14/2016           30        12        47                 29.95   
14  1/15/2016           43        31        62                 29.82   
15  1/16/2016           47        37        70                 29.52   
16  1/17/2016           36        23        66                 29.78   
17  1/18/2016           25         6        53                 29.83   
18  1/19/2016           22         3        42                 30.03   
19  1/20/2016           32        15        49                 30.13   
20  1/21/2016           31        11        45                 30.15   
21  1/22/2016           26         6        41                 30.21   
22  1/23/2016           26        21        78                 29.77   
23  1/24/2016           28        11        53                 29.92   
24  1/25/2016           34        18        54                 30.25   
25  1/26/2016           43        29        56                 30.03   
26  1/27/2016           41        22        45                 30.03   
27  1/28/2016           37        20        51                 29.90   
28  1/29/2016           36        21        50                 29.58   
29  1/30/2016           34        16        46                 30.01   
30  1/31/2016           46        28        52                 29.90   

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover    Events  \
0                10           8.0               0           5       NaN   
1                10           7.0               0           3       NaN   
2                10           8.0               0           1       NaN   
3                10           9.0               0           3       NaN   
4                10           5.0               0           0       NaN   
5                10           4.0               0           0       NaN   
6                10           2.0               0           3       NaN   
7                10           4.0               0           8       NaN   
8                 9           8.0               T           8      Rain   
9                 4           NaN             1.8           7      Rain   
10               10           NaN               0           1       NaN   
11               10           6.0               T           4       NaN   
12               10          10.0               0           0       NaN   
13               10           5.0               T           7       NaN   
14                9           5.0               T           2       NaN   
15                8           7.0            0.24           7      Rain   
16                8           6.0            0.05           6  Fog-Snow   
17                9          12.0               T           2      Snow   
18               10          11.0               0           1       NaN   
19               10           6.0               0           2       NaN   
20               10           6.0               0           1       NaN   
21                9           NaN            0.01      

In [ ]:
df.head() #see 5 row of starting

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0  1/1/2016           38        23        52                 30.03   
1  1/2/2016           36        18        46                 30.02   
2  1/3/2016           40        21        47                 29.86   
3  1/4/2016           25         9        44                 30.05   
4  1/5/2016           20        -3        41                 30.57   

   VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
0               10           8.0               0           5    NaN   
1               10           7.0               0           3    NaN   
2               10           8.0               0           1    NaN   
3               10           9.0               0           3    NaN   
4               10           5.0               0           0    NaN   

   WindDirDegrees  
0             281  
1             275  
2             277  
3             345  
4             333

In [ ]:
df.head(10)  #see 5 row of starting

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0   1/1/2016           38        23        52                 30.03   
1   1/2/2016           36        18        46                 30.02   
2   1/3/2016           40        21        47                 29.86   
3   1/4/2016           25         9        44                 30.05   
4   1/5/2016           20        -3        41                 30.57   
5   1/6/2016           33         4        35                 30.50   
6   1/7/2016           39        11        33                 30.28   
7   1/8/2016           39        29        64                 30.20   
8   1/9/2016           44        38        77                 30.16   
9  1/10/2016           50        46        71                 29.59   

   VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
0               10           8.0               0           5    NaN   
1               10           7.0               0           3    NaN   
2               10           8.0               0           1    NaN   
3               10           9.0               0           3    NaN   
4               10           5.0               0           0    NaN   
5               10           4.0               0           0    NaN   
6               10           2.0               0           3    NaN   
7               10           4.0               0           8    NaN   
8                9           8.0               T           8   Rain   
9                4           NaN             1.8           7   Rain   

   WindDirDegrees  
0             281  
1             275  
2             277  
3             345  
4             333  
5             259  
6             293  
7              79  
8              76  
9             109

In [ ]:
df.tail() #see 5 col of ending

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
26  1/27/2016           41        22        45                 30.03   
27  1/28/2016           37        20        51                 29.90   
28  1/29/2016           36        21        50                 29.58   
29  1/30/2016           34        16        46                 30.01   
30  1/31/2016           46        28        52                 29.90   

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
26               10           7.0               T           3   Rain   
27               10           5.0               0           1    NaN   
28               10           8.0               0           4    NaN   
29               10           7.0               0           0    NaN   
30               10           5.0               0           0    NaN   

    WindDirDegrees  
26             311  
27             234  
28             298  
29             257  
30             241

In [ ]:
df.columns

Index(['EST', 'Temperature', 'DewPoint', 'Humidity', 'Sea Level PressureIn',
       'VisibilityMiles', 'WindSpeedMPH', 'PrecipitationIn', 'CloudCover',
       'Events', 'WindDirDegrees'],
      dtype='object')

In [ ]:
# col ,attribute , feature same
#ekta certain col access korte chaile (dot .) diye and (of [] ) diye
#quary korar jnno (of--> [] ) usekorbo
#dot use korbo choto name er attribute er khetre

In [ ]:
#df.Temperature
#df['Temperature']
#same

In [ ]:
df.Temperature, df[['EST','Temperature']]

(0     38
 1     36
 2     40
 3     25
 4     20
 5     33
 6     39
 7     39
 8     44
 9     50
 10    33
 11    35
 12    26
 13    30
 14    43
 15    47
 16    36
 17    25
 18    22
 19    32
 20    31
 21    26
 22    26
 23    28
 24    34
 25    43
 26    41
 27    37
 28    36
 29    34
 30    46
 Name: Temperature, dtype: int64,
           EST  Temperature
 0    1/1/2016           38
 1    1/2/2016           36
 2    1/3/2016           40
 3    1/4/2016           25
 4    1/5/2016           20
 5    1/6/2016           33
 6    1/7/2016           39
 7    1/8/2016           39
 8    1/9/2016           44
 9   1/10/2016           50
 10  1/11/2016           33
 11  1/12/2016           35
 12  1/13/2016           26
 13  1/14/2016           30
 14  1/15/2016           43
 15  1/16/2016           47
 16  1/17/2016           36
 17  1/18/2016           25
 18  1/19/2016           22
 19  1/20/2016           32
 20  1/21/2016           31
 21  1/22/2016           26
 22  1/23/20

In [ ]:
df.Temperature.max(), df.Temperature.min(), df.Temperature.mean()

(50, 20, np.float64(34.67741935483871))

In [ ]:
df['Temperature'].max(),df['Temperature'].min(),df['Temperature'].mean()

(50, 20, np.float64(34.67741935483871))

In [ ]:
df.loc[2] # 2 no row

EST                     1/3/2016
Temperature                   40
DewPoint                      21
Humidity                      47
Sea Level PressureIn       29.86
VisibilityMiles               10
WindSpeedMPH                 8.0
PrecipitationIn                0
CloudCover                     1
Events                       NaN
WindDirDegrees               277
Name: 2, dtype: object

In [ ]:
df.loc[1:5] # dataframe slicing
# see row 1 to 5

# iloc dile index based location , 2d slicing
#row col duitai slicing kora jay

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
1  1/2/2016           36        18        46                 30.02   
2  1/3/2016           40        21        47                 29.86   
3  1/4/2016           25         9        44                 30.05   
4  1/5/2016           20        -3        41                 30.57   
5  1/6/2016           33         4        35                 30.50   

   VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
1               10           7.0               0           3    NaN   
2               10           8.0               0           1    NaN   
3               10           9.0               0           3    NaN   
4               10           5.0               0           0    NaN   
5               10           4.0               0           0    NaN   

   WindDirDegrees  
1             275  
2             277  
3             345  
4             333  
5             259

In [ ]:
df.iloc[2:4]  # row 2 to 3

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
2  1/3/2016           40        21        47                 29.86   
3  1/4/2016           25         9        44                 30.05   

   VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
2               10           8.0               0           1    NaN   
3               10           9.0               0           3    NaN   

   WindDirDegrees  
2             277  
3             345

In [ ]:
df.loc[2:6]

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
2  1/3/2016           40        21        47                 29.86   
3  1/4/2016           25         9        44                 30.05   
4  1/5/2016           20        -3        41                 30.57   
5  1/6/2016           33         4        35                 30.50   
6  1/7/2016           39        11        33                 30.28   

   VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
2               10           8.0               0           1    NaN   
3               10           9.0               0           3    NaN   
4               10           5.0               0           0    NaN   
5               10           4.0               0           0    NaN   
6               10           2.0               0           3    NaN   

   WindDirDegrees  
2             277  
3             345  
4             333  
5             259  
6             293

In [ ]:
df.iloc[2:6]

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
2  1/3/2016           40        21        47                 29.86   
3  1/4/2016           25         9        44                 30.05   
4  1/5/2016           20        -3        41                 30.57   
5  1/6/2016           33         4        35                 30.50   

   VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
2               10           8.0               0           1    NaN   
3               10           9.0               0           3    NaN   
4               10           5.0               0           0    NaN   
5               10           4.0               0           0    NaN   

   WindDirDegrees  
2             277  
3             345  
4             333  
5             259

In [ ]:
#loc --->>> start to end
#iloc --->>> start to end-1


In [ ]:
df.iloc[2:5,1:5]      # for slice {both row and col only iloc work}

#row 2 to 5. col 1 to 5




Temperature  DewPoint  Humidity  Sea Level PressureIn
2           40        21        47                 29.86
3           25         9        44                 30.05
4           20        -3        41                 30.57

In [ ]:
df.loc[1:5,3:5]

TypeError: cannot do slice indexing on Index with these indexers [3] of type int

In [ ]:
df.Events.unique()  #Events col e ki ki unique value ache dekha jay

array([nan, 'Rain', 'Fog-Snow', 'Snow'], dtype=object)

In [ ]:
#Database Query

In [ ]:
df['EST']

0      1/1/2016
1      1/2/2016
2      1/3/2016
3      1/4/2016
4      1/5/2016
5      1/6/2016
6      1/7/2016
7      1/8/2016
8      1/9/2016
9     1/10/2016
10    1/11/2016
11    1/12/2016
12    1/13/2016
13    1/14/2016
14    1/15/2016
15    1/16/2016
16    1/17/2016
17    1/18/2016
18    1/19/2016
19    1/20/2016
20    1/21/2016
21    1/22/2016
22    1/23/2016
23    1/24/2016
24    1/25/2016
25    1/26/2016
26    1/27/2016
27    1/28/2016
28    1/29/2016
29    1/30/2016
30    1/31/2016
Name: EST, dtype: object

In [ ]:
df['EST'][df['Events']=='Rain']
#df of est where df[event]='rain'
#2nd [] eta diye where bujhacche

8      1/9/2016
9     1/10/2016
15    1/16/2016
26    1/27/2016
Name: EST, dtype: object

In [ ]:
df[['EST','Temperature']][df['Events']=='Rain']
#df theke 2ta column dekhabe (est , temp ), where events=rain


EST  Temperature
8    1/9/2016           44
9   1/10/2016           50
15  1/16/2016           47
26  1/27/2016           41

In [ ]:
df[df['Events']=='Rain']
#df where events=rain
# jei third bracket er moddhe condition ache seta where bolbo


EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
8    1/9/2016           44        38        77                 30.16   
9   1/10/2016           50        46        71                 29.59   
15  1/16/2016           47        37        70                 29.52   
26  1/27/2016           41        22        45                 30.03   

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
8                 9           8.0               T           8   Rain   
9                 4           NaN             1.8           7   Rain   
15                8           7.0            0.24           7   Rain   
26               10           7.0               T           3   Rain   

    WindDirDegrees  
8               76  
9              109  
15             340  
26             311

In [ ]:
df.isnull().sum()
# jokhon ml model e null value fit korbo tokhon model e bad effect felbe , seta eraite amra isnull diye check korbo null value ache kina



EST                      0
Temperature              0
DewPoint                 0
Humidity                 0
Sea Level PressureIn     0
VisibilityMiles          0
WindSpeedMPH             3
PrecipitationIn          0
CloudCover               0
Events                  22
WindDirDegrees           0
dtype: int64

In [ ]:
df['Sea Level PressureIn'].max()

30.57

In [ ]:
df.fillna(1, inplace=True)
#nun value fill kora hoy and inplace=true diye df e save kora hoy

In [ ]:
df

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0    1/1/2016           38        23        52                 30.03   
1    1/2/2016           36        18        46                 30.02   
2    1/3/2016           40        21        47                 29.86   
3    1/4/2016           25         9        44                 30.05   
4    1/5/2016           20        -3        41                 30.57   
5    1/6/2016           33         4        35                 30.50   
6    1/7/2016           39        11        33                 30.28   
7    1/8/2016           39        29        64                 30.20   
8    1/9/2016           44        38        77                 30.16   
9   1/10/2016           50        46        71                 29.59   
10  1/11/2016           33         8        37                 29.92   
11  1/12/2016           35        15        53                 29.85   
12  1/13/2016           26         4        42                 29.94   
13  1/14/2016           30        12        47                 29.95   
14  1/15/2016           43        31        62                 29.82   
15  1/16/2016           47        37        70                 29.52   
16  1/17/2016           36        23        66                 29.78   
17  1/18/2016           25         6        53                 29.83   
18  1/19/2016           22         3        42                 30.03   
19  1/20/2016           32        15        49                 30.13   
20  1/21/2016           31        11        45                 30.15   
21  1/22/2016           26         6        41                 30.21   
22  1/23/2016           26        21        78                 29.77   
23  1/24/2016           28        11        53                 29.92   
24  1/25/2016           34        18        54                 30.25   
25  1/26/2016           43        29        56                 30.03   
26  1/27/2016           41        22        45                 30.03   
27  1/28/2016           37        20        51                 29.90   
28  1/29/2016           36        21        50                 29.58   
29  1/30/2016           34        16        46                 30.01   
30  1/31/2016           46        28        52                 29.90   

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover    Events  \
0                10           8.0               0           5         1   
1                10           7.0               0           3         1   
2                10           8.0               0           1         1   
3                10           9.0               0           3         1   
4                10           5.0               0           0         1   
5                10           4.0               0           0         1   
6                10           2.0               0           3         1   
7                10           4.0               0           8         1   
8                 9           8.0               T           8      Rain   
9                 4           1.0             1.8           7      Rain   
10               10           1.0               0           1         1   
11               10           6.0               T           4         1   
12               10          10.0               0           0         1   
13               10           5.0               T           7         1   
14                9           5.0               T           2         1   
15                8           7.0            0.24           7      Rain   
16                8           6.0            0.05           6  Fog-Snow   
17                9          12.0               T           2      Snow   
18               10          11.0               0           1         1   
19               10           6.0               0           2         1   
20               10           6.0               0           1         1   
21                9           1.0            0.01      

In [ ]:
df.isnull().sum()

EST                     0
Temperature             0
DewPoint                0
Humidity                0
Sea Level PressureIn    0
VisibilityMiles         0
WindSpeedMPH            0
PrecipitationIn         0
CloudCover              0
Events                  0
WindDirDegrees          0
dtype: int64

In [ ]:
df.interpolate()
#randomly value asign na kore age porer value bujhe majher nan value gulo fill korbe

/tmp/ipython-input-2206132117.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate()


EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0    1/1/2016           38        23        52                 30.03   
1    1/2/2016           36        18        46                 30.02   
2    1/3/2016           40        21        47                 29.86   
3    1/4/2016           25         9        44                 30.05   
4    1/5/2016           20        -3        41                 30.57   
5    1/6/2016           33         4        35                 30.50   
6    1/7/2016           39        11        33                 30.28   
7    1/8/2016           39        29        64                 30.20   
8    1/9/2016           44        38        77                 30.16   
9   1/10/2016           50        46        71                 29.59   
10  1/11/2016           33         8        37                 29.92   
11  1/12/2016           35        15        53                 29.85   
12  1/13/2016           26         4        42                 29.94   
13  1/14/2016           30        12        47                 29.95   
14  1/15/2016           43        31        62                 29.82   
15  1/16/2016           47        37        70                 29.52   
16  1/17/2016           36        23        66                 29.78   
17  1/18/2016           25         6        53                 29.83   
18  1/19/2016           22         3        42                 30.03   
19  1/20/2016           32        15        49                 30.13   
20  1/21/2016           31        11        45                 30.15   
21  1/22/2016           26         6        41                 30.21   
22  1/23/2016           26        21        78                 29.77   
23  1/24/2016           28        11        53                 29.92   
24  1/25/2016           34        18        54                 30.25   
25  1/26/2016           43        29        56                 30.03   
26  1/27/2016           41        22        45                 30.03   
27  1/28/2016           37        20        51                 29.90   
28  1/29/2016           36        21        50                 29.58   
29  1/30/2016           34        16        46                 30.01   
30  1/31/2016           46        28        52                 29.90   

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover    Events  \
0                10           8.0               0           5         1   
1                10           7.0               0           3         1   
2                10           8.0               0           1         1   
3                10           9.0               0           3         1   
4                10           5.0               0           0         1   
5                10           4.0               0           0         1   
6                10           2.0               0           3         1   
7                10           4.0               0           8         1   
8                 9           8.0               T           8      Rain   
9                 4           1.0             1.8           7      Rain   
10               10           1.0               0           1         1   
11               10           6.0               T           4         1   
12               10          10.0               0           0         1   
13               10           5.0               T           7         1   
14                9           5.0               T           2         1   
15                8           7.0            0.24           7      Rain   
16                8           6.0            0.05           6  Fog-Snow   
17                9          12.0               T           2      Snow   
18               10          11.0               0           1         1   
19               10           6.0               0           2         1   
20               10           6.0               0           1         1   
21                9           1.0            0.01      

In [ ]:
import numpy as np

In [ ]:
df.replace(1, np.nan, inplace=True)

In [ ]:
df

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0    1/1/2016           38        23        52                 30.03   
1    1/2/2016           36        18        46                 30.02   
2    1/3/2016           40        21        47                 29.86   
3    1/4/2016           25         9        44                 30.05   
4    1/5/2016           20        -3        41                 30.57   
5    1/6/2016           33         4        35                 30.50   
6    1/7/2016           39        11        33                 30.28   
7    1/8/2016           39        29        64                 30.20   
8    1/9/2016           44        38        77                 30.16   
9   1/10/2016           50        46        71                 29.59   
10  1/11/2016           33         8        37                 29.92   
11  1/12/2016           35        15        53                 29.85   
12  1/13/2016           26         4        42                 29.94   
13  1/14/2016           30        12        47                 29.95   
14  1/15/2016           43        31        62                 29.82   
15  1/16/2016           47        37        70                 29.52   
16  1/17/2016           36        23        66                 29.78   
17  1/18/2016           25         6        53                 29.83   
18  1/19/2016           22         3        42                 30.03   
19  1/20/2016           32        15        49                 30.13   
20  1/21/2016           31        11        45                 30.15   
21  1/22/2016           26         6        41                 30.21   
22  1/23/2016           26        21        78                 29.77   
23  1/24/2016           28        11        53                 29.92   
24  1/25/2016           34        18        54                 30.25   
25  1/26/2016           43        29        56                 30.03   
26  1/27/2016           41        22        45                 30.03   
27  1/28/2016           37        20        51                 29.90   
28  1/29/2016           36        21        50                 29.58   
29  1/30/2016           34        16        46                 30.01   
30  1/31/2016           46        28        52                 29.90   

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover    Events  \
0              10.0           8.0               0         5.0       NaN   
1              10.0           7.0               0         3.0       NaN   
2              10.0           8.0               0         NaN       NaN   
3              10.0           9.0               0         3.0       NaN   
4              10.0           5.0               0         0.0       NaN   
5              10.0           4.0               0         0.0       NaN   
6              10.0           2.0               0         3.0       NaN   
7              10.0           4.0               0         8.0       NaN   
8               9.0           8.0               T         8.0      Rain   
9               4.0           NaN             1.8         7.0      Rain   
10             10.0           NaN               0         NaN       NaN   
11             10.0           6.0               T         4.0       NaN   
12             10.0          10.0               0         0.0       NaN   
13             10.0           5.0               T         7.0       NaN   
14              9.0           5.0               T         2.0       NaN   
15              8.0           7.0            0.24         7.0      Rain   
16              8.0           6.0            0.05         6.0  Fog-Snow   
17              9.0          12.0               T         2.0      Snow   
18             10.0          11.0               0         NaN       NaN   
19             10.0           6.0               0         2.0       NaN   
20             10.0           6.0               0         NaN       NaN   
21              9.0           NaN            0.01      

In [ ]:
df.interpolate()

/tmp/ipython-input-4002874584.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate()


EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0    1/1/2016           38        23        52                 30.03   
1    1/2/2016           36        18        46                 30.02   
2    1/3/2016           40        21        47                 29.86   
3    1/4/2016           25         9        44                 30.05   
4    1/5/2016           20        -3        41                 30.57   
5    1/6/2016           33         4        35                 30.50   
6    1/7/2016           39        11        33                 30.28   
7    1/8/2016           39        29        64                 30.20   
8    1/9/2016           44        38        77                 30.16   
9   1/10/2016           50        46        71                 29.59   
10  1/11/2016           33         8        37                 29.92   
11  1/12/2016           35        15        53                 29.85   
12  1/13/2016           26         4        42                 29.94   
13  1/14/2016           30        12        47                 29.95   
14  1/15/2016           43        31        62                 29.82   
15  1/16/2016           47        37        70                 29.52   
16  1/17/2016           36        23        66                 29.78   
17  1/18/2016           25         6        53                 29.83   
18  1/19/2016           22         3        42                 30.03   
19  1/20/2016           32        15        49                 30.13   
20  1/21/2016           31        11        45                 30.15   
21  1/22/2016           26         6        41                 30.21   
22  1/23/2016           26        21        78                 29.77   
23  1/24/2016           28        11        53                 29.92   
24  1/25/2016           34        18        54                 30.25   
25  1/26/2016           43        29        56                 30.03   
26  1/27/2016           41        22        45                 30.03   
27  1/28/2016           37        20        51                 29.90   
28  1/29/2016           36        21        50                 29.58   
29  1/30/2016           34        16        46                 30.01   
30  1/31/2016           46        28        52                 29.90   

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover    Events  \
0              10.0      8.000000               0         5.0       NaN   
1              10.0      7.000000               0         3.0       NaN   
2              10.0      8.000000               0         3.0       NaN   
3              10.0      9.000000               0         3.0       NaN   
4              10.0      5.000000               0         0.0       NaN   
5              10.0      4.000000               0         0.0       NaN   
6              10.0      2.000000               0         3.0       NaN   
7              10.0      4.000000               0         8.0       NaN   
8               9.0      8.000000               T         8.0      Rain   
9               4.0      7.333333             1.8         7.0      Rain   
10             10.0      6.666667               0         5.5       NaN   
11             10.0      6.000000               T         4.0       NaN   
12             10.0     10.000000               0         0.0       NaN   
13             10.0      5.000000               T         7.0       NaN   
14              9.0      5.000000               T         2.0       NaN   
15              8.0      7.000000            0.24         7.0      Rain   
16              8.0      6.000000            0.05         6.0  Fog-Snow   
17              9.0     12.000000               T         2.0      Snow   
18             10.0     11.000000               0         2.0       NaN   
19             10.0      6.000000               0         2.0       NaN   
20             10.0      6.000000               0         2.5       NaN   
21              9.0     11.000000            0.01      

In [ ]:
#important xm er jonno
import pandas as pd
weather_data = {
    'day': ['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'temperature': [32,35,28,24,32,31],
    'windspeed': [6,7,2,7,4,2],
    'event': ['Rain', 'Sunny', 'Snow','Snow','Rain', 'Sunny']
}
df = pd.DataFrame(weather_data)
# df = pd.read_csv("weather_data.csv")
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [ ]:
df[1:4]

day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow

In [ ]:
df.loc[1:4]

day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

In [ ]:
df.iloc[0:4]

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow

In [ ]:
df = pd.DataFrame(weather_data, columns['a','b','c','d'])
# df = pd.read_csv("weather_data.csv")
df

NameError: name 'columns' is not defined

In [ ]:
df['day'][df['temperature'] == df['temperature'].max()]
##day ta dekhao jokhon temp max ache

1    1/2/2017
Name: day, dtype: object

In [ ]:
df['temperature'].max()

35

In [ ]:
df[df['temperature'] == df['temperature'].max()]
#puro dataframe dekhabe

day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

In [ ]:
df.describe() #include='O'

temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

In [ ]:
df.describe(include='O')
#string analysis

day event
count          6     6
unique         6     3
top     1/1/2017  Rain
freq           1     2

In [ ]:
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [ ]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [ ]:
df.set_index('day', inplace=True)
#index set kora as day

In [ ]:
df.columns

Index(['temperature', 'windspeed', 'event'], dtype='object')

In [ ]:
df.index

Index(['1/1/2017', '1/2/2017', '1/3/2017', '1/4/2017', '1/5/2017', '1/6/2017'], dtype='object', name='day')

In [ ]:
df

temperature  windspeed  event
day                                    
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           31          2  Sunny

In [ ]:
df.loc["1/1/2017":"1/4/2017"]

temperature  windspeed  event
day                                    
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow

In [ ]:
df.reset_index(inplace=True) #index reset kora
df

index       day  temperature  windspeed  event
0      0  1/1/2017           32          6   Rain
1      1  1/2/2017           35          7  Sunny
2      2  1/3/2017           28          2   Snow
3      3  1/4/2017           24          7   Snow
4      4  1/5/2017           32          4   Rain
5      5  1/6/2017           31          2  Sunny

In [ ]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [ ]:
df = pd.read_excel("weather_data.xlsx")
df

day  temperature  windspeed  event
0 2017-01-01           32          6   Rain
1 2017-01-02           35          7  Sunny
2 2017-01-03           28          2   Snow

In [ ]:
df.columns = ['d','t','w','e'] # same no of col e dity hbe
df

d   t  w      e
0 2017-01-01  32  6   Rain
1 2017-01-02  35  7  Sunny
2 2017-01-03  28  2   Snow

In [ ]:
df

d   t  w      e
0 2017-01-01  32  6   Rain
1 2017-01-02  35  7  Sunny
2 2017-01-03  28  2   Snow

In [ ]:
tt = pd.read_csv('weather.csv')

In [ ]:
tt

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0    1/1/2016           38        23        52                 30.03   
1    1/2/2016           36        18        46                 30.02   
2    1/3/2016           40        21        47                 29.86   
3    1/4/2016           25         9        44                 30.05   
4    1/5/2016           20        -3        41                 30.57   
5    1/6/2016           33         4        35                 30.50   
6    1/7/2016           39        11        33                 30.28   
7    1/8/2016           39        29        64                 30.20   
8    1/9/2016           44        38        77                 30.16   
9   1/10/2016           50        46        71                 29.59   
10  1/11/2016           33         8        37                 29.92   
11  1/12/2016           35        15        53                 29.85   
12  1/13/2016           26         4        42                 29.94   
13  1/14/2016           30        12        47                 29.95   
14  1/15/2016           43        31        62                 29.82   
15  1/16/2016           47        37        70                 29.52   
16  1/17/2016           36        23        66                 29.78   
17  1/18/2016           25         6        53                 29.83   
18  1/19/2016           22         3        42                 30.03   
19  1/20/2016           32        15        49                 30.13   
20  1/21/2016           31        11        45                 30.15   
21  1/22/2016           26         6        41                 30.21   
22  1/23/2016           26        21        78                 29.77   
23  1/24/2016           28        11        53                 29.92   
24  1/25/2016           34        18        54                 30.25   
25  1/26/2016           43        29        56                 30.03   
26  1/27/2016           41        22        45                 30.03   
27  1/28/2016           37        20        51                 29.90   
28  1/29/2016           36        21        50                 29.58   
29  1/30/2016           34        16        46                 30.01   
30  1/31/2016           46        28        52                 29.90   

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover    Events  \
0                10           8.0               0           5       NaN   
1                10           7.0               0           3       NaN   
2                10           8.0               0           1       NaN   
3                10           9.0               0           3       NaN   
4                10           5.0               0           0       NaN   
5                10           4.0               0           0       NaN   
6                10           2.0               0           3       NaN   
7                10           4.0               0           8       NaN   
8                 9           8.0               T           8      Rain   
9                 4           NaN             1.8           7      Rain   
10               10           NaN               0           1       NaN   
11               10           6.0               T           4       NaN   
12               10          10.0               0           0       NaN   
13               10           5.0               T           7       NaN   
14                9           5.0               T           2       NaN   
15                8           7.0            0.24           7      Rain   
16                8           6.0            0.05           6  Fog-Snow   
17                9          12.0               T           2      Snow   
18               10          11.0               0           1       NaN   
19               10           6.0               0           2       NaN   
20               10           6.0               0           1       NaN   
21                9           NaN            0.01      

In [ ]:
tt.head(

)

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0  1/1/2016           38        23        52                 30.03   
1  1/2/2016           36        18        46                 30.02   
2  1/3/2016           40        21        47                 29.86   
3  1/4/2016           25         9        44                 30.05   
4  1/5/2016           20        -3        41                 30.57   

   VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
0               10           8.0               0           5    NaN   
1               10           7.0               0           3    NaN   
2               10           8.0               0           1    NaN   
3               10           9.0               0           3    NaN   
4               10           5.0               0           0    NaN   

   WindDirDegrees  
0             281  
1             275  
2             277  
3             345  
4             333

In [ ]:
tt[5:10]

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
5   1/6/2016           33         4        35                 30.50   
6   1/7/2016           39        11        33                 30.28   
7   1/8/2016           39        29        64                 30.20   
8   1/9/2016           44        38        77                 30.16   
9  1/10/2016           50        46        71                 29.59   

   VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
5               10           4.0               0           0    NaN   
6               10           2.0               0           3    NaN   
7               10           4.0               0           8    NaN   
8                9           8.0               T           8   Rain   
9                4           NaN             1.8           7   Rain   

   WindDirDegrees  
5             259  
6             293  
7              79  
8              76  
9             109

In [ ]:
tt.loc[5:9]

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
5   1/6/2016           33         4        35                 30.50   
6   1/7/2016           39        11        33                 30.28   
7   1/8/2016           39        29        64                 30.20   
8   1/9/2016           44        38        77                 30.16   
9  1/10/2016           50        46        71                 29.59   

   VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
5               10           4.0               0           0    NaN   
6               10           2.0               0           3    NaN   
7               10           4.0               0           8    NaN   
8                9           8.0               T           8   Rain   
9                4           NaN             1.8           7   Rain   

   WindDirDegrees  
5             259  
6             293  
7              79  
8              76  
9             109

In [ ]:
tt.iloc[5:10]

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
5   1/6/2016           33         4        35                 30.50   
6   1/7/2016           39        11        33                 30.28   
7   1/8/2016           39        29        64                 30.20   
8   1/9/2016           44        38        77                 30.16   
9  1/10/2016           50        46        71                 29.59   

   VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
5               10           4.0               0           0    NaN   
6               10           2.0               0           3    NaN   
7               10           4.0               0           8    NaN   
8                9           8.0               T           8   Rain   
9                4           NaN             1.8           7   Rain   

   WindDirDegrees  
5             259  
6             293  
7              79  
8              76  
9             109

In [ ]:
tt['Events']

0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
6          NaN
7          NaN
8         Rain
9         Rain
10         NaN
11         NaN
12         NaN
13         NaN
14         NaN
15        Rain
16    Fog-Snow
17        Snow
18         NaN
19         NaN
20         NaN
21        Snow
22    Fog-Snow
23        Snow
24         NaN
25         NaN
26        Rain
27         NaN
28         NaN
29         NaN
30         NaN
Name: Events, dtype: object

In [ ]:
tt['Events'].dtype

dtype('O')

In [ ]:
type(tt['Events'])

pandas.core.series.Series

In [ ]:
df=pd.read_excel("weather_data.xlsx","Sheet1")

In [ ]:
df

day  temperature  windspeed  event
0 2017-01-01           32          6   Rain
1 2017-01-02           35          7  Sunny
2 2017-01-03           28          2   Snow

ঠিক আছে 😄 একদম ক্লিয়ার করে দিচ্ছি 👇

```python
("weather_data.xlsx", "Sheet1")
```

এই দুইটার মানে আলাদা আলাদা 👇

---

### 1️⃣ `"weather_data.xlsx"`

👉 **Excel ফাইলের নাম**

* এটা বলে দিচ্ছে:
  ➜ কোন ফাইল থেকে ডাটা পড়বে
* এই ফাইলটা তোমার current folder-এ থাকতে হবে
  (না থাকলে error আসবে)

---

### 2️⃣ `"Sheet1"`

👉 **Excel ফাইলের ভিতরের sheet-এর নাম**

একটা Excel ফাইলে একাধিক sheet থাকতে পারে, যেমন:

* Sheet1
* Sheet2
* JanuaryData

এখানে বলা হচ্ছে:
➜ **Sheet1 থেকে ডাটা পড়ো**

---

### একসাথে পড়লে মানে দাঁড়ায়

```python
pd.read_excel("weather_data.xlsx", "Sheet1")
```

👉 “weather_data.xlsx ফাইলের **Sheet1** থেকে ডাটা পড়ে আনো”

---

### যদি `"Sheet1"` না দাও?

```python
pd.read_excel("weather_data.xlsx")
```

👉 Excel-এর **প্রথম sheet** নিজে নিজে পড়বে

---

### যদি sheet নাম ভুল হয়?

❌ error আসবে, কারণ ওই নামের sheet নাই

---

### ছোট তুলনা (real life)

ধরো:

* 📁 **weather_data.xlsx** = একটা বই
* 📄 **Sheet1** = বইয়ের একটা পাতা

তুমি বলছো:

> “এই বইয়ের এই পাতাটা পড়ো”

---

এখন বুঝছো তো? 😊
চাও তো আমি **folder path**, **multiple sheets**, বা **sheet index (0,1)** দিয়েও বুঝাতে পারি।


In [ ]:
df

day  temperature  windspeed  event
0 2017-01-01           32          6   Rain
1 2017-01-02           35          7  Sunny
2 2017-01-03           28          2   Snow

In [ ]:
#Ways of creating dataframes

In [ ]:
#using csv

In [ ]:
dc = pd.read_csv("weather.csv")
dc

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0    1/1/2016           38        23        52                 30.03   
1    1/2/2016           36        18        46                 30.02   
2    1/3/2016           40        21        47                 29.86   
3    1/4/2016           25         9        44                 30.05   
4    1/5/2016           20        -3        41                 30.57   
5    1/6/2016           33         4        35                 30.50   
6    1/7/2016           39        11        33                 30.28   
7    1/8/2016           39        29        64                 30.20   
8    1/9/2016           44        38        77                 30.16   
9   1/10/2016           50        46        71                 29.59   
10  1/11/2016           33         8        37                 29.92   
11  1/12/2016           35        15        53                 29.85   
12  1/13/2016           26         4        42                 29.94   
13  1/14/2016           30        12        47                 29.95   
14  1/15/2016           43        31        62                 29.82   
15  1/16/2016           47        37        70                 29.52   
16  1/17/2016           36        23        66                 29.78   
17  1/18/2016           25         6        53                 29.83   
18  1/19/2016           22         3        42                 30.03   
19  1/20/2016           32        15        49                 30.13   
20  1/21/2016           31        11        45                 30.15   
21  1/22/2016           26         6        41                 30.21   
22  1/23/2016           26        21        78                 29.77   
23  1/24/2016           28        11        53                 29.92   
24  1/25/2016           34        18        54                 30.25   
25  1/26/2016           43        29        56                 30.03   
26  1/27/2016           41        22        45                 30.03   
27  1/28/2016           37        20        51                 29.90   
28  1/29/2016           36        21        50                 29.58   
29  1/30/2016           34        16        46                 30.01   
30  1/31/2016           46        28        52                 29.90   

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover    Events  \
0                10           8.0               0           5       NaN   
1                10           7.0               0           3       NaN   
2                10           8.0               0           1       NaN   
3                10           9.0               0           3       NaN   
4                10           5.0               0           0       NaN   
5                10           4.0               0           0       NaN   
6                10           2.0               0           3       NaN   
7                10           4.0               0           8       NaN   
8                 9           8.0               T           8      Rain   
9                 4           NaN             1.8           7      Rain   
10               10           NaN               0           1       NaN   
11               10           6.0               T           4       NaN   
12               10          10.0               0           0       NaN   
13               10           5.0               T           7       NaN   
14                9           5.0               T           2       NaN   
15                8           7.0            0.24           7      Rain   
16                8           6.0            0.05           6  Fog-Snow   
17                9          12.0               T           2      Snow   
18               10          11.0               0           1       NaN   
19               10           6.0               0           2       NaN   
20               10           6.0               0           1       NaN   
21                9           NaN            0.01      

In [ ]:
#using excel

In [ ]:
import pandas as pd

In [ ]:
ddf = pd.read_excel("weather_data.xlsx")
ddf


day  temperature  windspeed  event
0 2017-01-01           32          6   Rain
1 2017-01-02           35          7  Sunny
2 2017-01-03           28          2   Snow

In [ ]:
#using dictionary

In [ ]:
dic = {
    "nam" : ['a','b','c'],
    "roll" : [1,2,3],
    "cgpa" : [4,3,3.5]
}

dicc = pd.DataFrame(dic)

dicc

nam  roll  cgpa
0   a     1   4.0
1   b     2   3.0
2   c     3   3.5

In [ ]:
# Using tuples

In [ ]:
tap = [
    ('a',1,4),
    ('b',2,3),
    ('c',3,3.5)
]

tapp = pd.DataFrame(data = tap, columns = ['nam','roll','cg'])
tapp

nam  roll   cg
0   a     1  4.0
1   b     2  3.0
2   c     3  3.5

In [ ]:
# Using list of dictionaries

In [ ]:
lis  = [
    {'nam':'a' , 'roll':1 , 'cg' : 4},
    {'nam':'b' , 'roll':2 , 'cg' : 3},
    {'nam':'c' , 'roll':3 , 'cg' : 3.5}
]


liss = pd.DataFrame(data = lis , columns = ['nam','roll','cg'])
liss

nam  roll   cg
0   a     1  4.0
1   b     2  3.0
2   c     3  3.5

In [ ]:
#Read and Write Dataframes

In [ ]:
import pandas as pd

df = pd.read_csv("stock_data.csv")
df

tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [ ]:
df = pd.read_csv("stock_data.csv",skiprows=1)  #akdom surur row ta baad
df

GOOGL          27.82   87   845     larry page
0   WMT           4.61  484    65           n.a.
1  MSFT             -1   85    64     bill gates
2  RIL   not available   50  1023  mukesh ambani
3  TATA            5.6   -1  n.a.     ratan tata

In [ ]:
df = pd.read_csv("stock_data.csv",skiprows=3)  #akdom surur 3 ta row ta baad
df

MSFT             -1  85    64     bill gates
0  RIL   not available  50  1023  mukesh ambani
1  TATA            5.6  -1  n.a.     ratan tata

In [ ]:
df = pd.read_csv("stock_data.csv",header = 2) #direct 2 num row ke header kora
df

WMT           4.61  484    65           n.a.
0  MSFT             -1   85    64     bill gates
1  RIL   not available   50  1023  mukesh ambani
2  TATA            5.6   -1  n.a.     ratan tata

In [ ]:
df = pd.read_csv("stock_data.csv",header=None,names = ['a','b','c','d','e'])
df #header mane col name ami dia dibo.jeta chilo oita value hoiah jabe

a              b        c      d              e
0  tickers            eps  revenue  price         people
1    GOOGL          27.82       87    845     larry page
2      WMT           4.61      484     65           n.a.
3     MSFT             -1       85     64     bill gates
4     RIL   not available       50   1023  mukesh ambani
5     TATA            5.6       -1   n.a.     ratan tata

In [ ]:
df= pd.read_csv("stock_data.csv",nrows = 3)  # 1st 3 ta row nibo sudu
df

tickers    eps  revenue  price      people
0   GOOGL  27.82       87    845  larry page
1     WMT   4.61      484     65        n.a.
2    MSFT  -1.00       85     64  bill gates

In [ ]:
df

tickers    eps  revenue  price      people
0   GOOGL  27.82       87    845  larry page
1     WMT   4.61      484     65        n.a.
2    MSFT  -1.00       85     64  bill gates

In [ ]:
df = pd.read_csv('stock_data.csv',na_values = ["n.a."]) # n.a. joto value ase nan kore dibo
df

tickers            eps  revenue   price         people
0   GOOGL          27.82       87   845.0     larry page
1     WMT           4.61      484    65.0            NaN
2    MSFT             -1       85    64.0     bill gates
3    RIL   not available       50  1023.0  mukesh ambani
4    TATA            5.6       -1     NaN     ratan tata

In [ ]:
df

tickers            eps  revenue   price         people
0   GOOGL          27.82       87   845.0     larry page
1     WMT           4.61      484    65.0            NaN
2    MSFT             -1       85    64.0     bill gates
3    RIL   not available       50  1023.0  mukesh ambani
4    TATA            5.6       -1     NaN     ratan tata

In [ ]:
df = pd.read_csv("stock_data.csv",na_values=['-1'])
df

tickers            eps  revenue price         people
0   GOOGL          27.82     87.0   845     larry page
1     WMT           4.61    484.0    65           n.a.
2    MSFT            NaN     85.0    64     bill gates
3    RIL   not available     50.0  1023  mukesh ambani
4    TATA            5.6      NaN  n.a.     ratan tata

In [ ]:
df

tickers            eps  revenue price         people
0   GOOGL          27.82     87.0   845     larry page
1     WMT           4.61    484.0    65           n.a.
2    MSFT            NaN     85.0    64     bill gates
3    RIL   not available     50.0  1023  mukesh ambani
4    TATA            5.6      NaN  n.a.     ratan tata

In [ ]:
cf = pd.read_csv("stock_data.csv")

In [ ]:
cf

tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [ ]:
cf = pd.read_csv("stock_data.csv", na_values = {
    'eps' : [-1],
    'revenue' : [87],
    'price' : ['n.a.'],
})
cf

tickers            eps  revenue   price         people
0   GOOGL          27.82      NaN   845.0     larry page
1     WMT           4.61    484.0    65.0           n.a.
2    MSFT            NaN     85.0    64.0     bill gates
3    RIL   not available     50.0  1023.0  mukesh ambani
4    TATA            5.6     -1.0     NaN     ratan tata

In [ ]:
df = pd.read_csv('new.csv')
df

tickers    eps  revenue price         people
0   GOOGL  27.82     87.0   845     larry page
1     WMT   4.61    484.0    65            NaN
2    MSFT  -1.00     85.0    64     bill gates
3    RIL     NaN     50.0  1023  mukesh ambani
4    TATA   5.60      NaN  n.a.     ratan tata

In [ ]:
gf = pd.read_csv('new.csv')
gf.to_csv('new.csv', index = False)
gf

tickers    eps  revenue price         people
0   GOOGL  27.82     87.0   845     larry page
1     WMT   4.61    484.0    65            NaN
2    MSFT  -1.00     85.0    64     bill gates
3    RIL     NaN     50.0  1023  mukesh ambani
4    TATA   5.60      NaN  n.a.     ratan tata

In [ ]:
gf.to_csv("new2.csv",header=1)
gf

tickers    eps  revenue price         people
0   GOOGL  27.82     87.0   845     larry page
1     WMT   4.61    484.0    65            NaN
2    MSFT  -1.00     85.0    64     bill gates
3    RIL     NaN     50.0  1023  mukesh ambani
4    TATA   5.60      NaN  n.a.     ratan tata

In [ ]:


'''
problem


df.to_csv("new.csv", index=False)
df.to_csv("new2.csv",header=False)
df.to_csv("new3.csv", columns=["tickers","price"], index=False)
df.to_excel("new.xlsx", sheet_name="stocks", index=False, startrow=2, startcol=1)


'''


In [ ]:
# Write two dataframes to two separate sheets in excel

In [ ]:
import pandas as pd

In [ ]:

df_stocks = pd.DataFrame({
    'tickers': ['GOOGL', 'WMT', 'MSFT'],
    'price': [845, 65, 64 ],
    'pe': [30.37, 14.26, 30.97],
    'eps': [27.82, 4.61, 2.12]
})

df_weather =  pd.DataFrame({
    'day': ['1/1/2017','1/2/2017','1/3/2017'],
    'temperature': [32,35,28],
    'event': ['Rain', 'Sunny', 'Snow']
})

In [ ]:
with pd.ExcelWriter('stocks_weather2.xlsx') as writer:
    df_stocks.to_excel(writer, sheet_name="stocks")
    df_weather.to_excel(writer, sheet_name="weather")

In [ ]:
student = {
     'nam' : ['a','b','c'],
     'roll' : [1,2,3]
 }
stu = pd.DataFrame(student)
stu

nam  roll
0   a     1
1   b     2
2   c     3

In [ ]:
teacher = {
    'nam' : ['d','e','f'],
    'pem' : [100,300,4000]
}
tec = pd.DataFrame(teacher)
tec

nam   pem
0   d   100
1   e   300
2   f  4000

In [ ]:
with pd.ExcelWriter('University.xlsx') as uni:
  stu.to_excel(uni,sheet_name='s1')
  tec.to_excel(uni,sheet_name='s2')

In [ ]:
df = pd.read_csv("stock_data.csv")
df

tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [ ]:
def convert_for_people(cell):
  if cell == 'n.a.':
    return 'Tusar'
  return cell

def convert_for_price(cell):
  if cell == 'n.a.':
    return 'Abdullah'
  return cell

df = pd.read_csv("stock_data.csv",converters={
    'people' : convert_for_people,
    'price' : convert_for_price
})

df

tickers            eps  revenue     price         people
0   GOOGL          27.82       87       845     larry page
1     WMT           4.61      484        65          Tusar
2    MSFT             -1       85        64     bill gates
3    RIL   not available       50      1023  mukesh ambani
4    TATA            5.6       -1  Abdullah     ratan tata

Q3 (Pandas: identify missing values)
Given a pandas DataFrame df, write code to print:

Missing value count per column/attribute/feature.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = {
    'a'  : [1,np.nan,3,4],
    'b'  : [np.nan,2,3,4],
    'c'  : [np.nan,2,np.nan,4]
}
df = pd.DataFrame(data)
df

a    b    c
0  1.0  NaN  NaN
1  NaN  2.0  2.0
2  3.0  3.0  NaN
3  4.0  4.0  4.0

In [ ]:
df.isnull().sum()

a    1
b    1
c    2
dtype: int64